# Generated by Django 3.1.2 on 2020-10-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20201022_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
    ]
