# Generated by Django 3.1.2 on 2020-10-23 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(default=datetime.datetime(2020, 10, 23, 8, 31, 7, 729810, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
