# Generated by Django 3.1.2 on 2020-10-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20201026_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('carfax', 'Carfax'), ('adverts', 'Adverts'), ('aparking', 'Aparking'), ('garage', 'Garage')], max_length=15),
        ),
    ]
