# Generated by Django 3.1.2 on 2020-10-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20201028_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_broadcast',
            field=models.BooleanField(),
        ),
    ]
