# Generated by Django 3.1.2 on 2020-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20201028_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
