# Generated by Django 3.1.2 on 2020-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20201028_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('carfax', 'Carfax'), ('adverts', 'Adverts'), ('aparking', 'Aparking'), ('garage', 'Garage'), ('request', 'Requests')], max_length=15),
        ),
    ]
