# Generated by Django 3.1.2 on 2020-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20201029_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('service', 'reference_id')},
        ),
    ]
